i18n/pt-BR/articles/inicializacao-da-aplicacao.md
Translating the file /i18n/pt-BR/articles/inicializacao-da-aplicacao.md from English to Brazilian Portuguese
=> Translate inicializacao-da-aplicacao.md to PT-BR

i18n/pt-BR/articles/ciclo-de-vida-full-stack.md
=> 📝 🚧 translation review

i18n/pt-BR/articles/como-usar-google-analytics-no-nullstack.md
=> Google Analytics article translation to pt-BR

i18n/pt-BR/articles/como-fazer-deploy-de-aplicacao-nullstack.md, i18n/pt-BR/articles/como-usar-facebook-pixel-no-nullstack.md
Tomei a liberdade de também mudar aquele "aplicação" em "Como fazer Deploy", se não entendi algo do contexto e afins pode dizer!
close #10
=> FB's Pixel article translation to pt-BR

i18n/pt-BR/articles/como-usar-mongodb-com-nullstack.md
Eita, agora que vi que não tem issue, tô assim já :sweat_smile:
Só quis completar aquela trindade de exemplos.
=> MongoDB article translation to pt-BR

i18n/pt-BR/articles/service-worker.md
Traduzindo a secção Service Worker da documentação para português
=> docs(service-worker): translating doc to pt-br

i18n/pt-BR/components/Home.yml
Comecei traduzindo as partes iniciais, ainda falta mais, dos quais farei com mais calma ao decorrer do tempo.
=> Início da tradução no componente /Home.yml

i18n/pt-BR/articles/contexto-secrets.md
Espero ter ajudado, o framework parece bem interessante, avante Brasil!
=> Tradução da documentação de secrets

i18n/pt-BR/articles/componentes-com-estado.md
=> Tradução para i18n\pt-BR\articles\componentes-com-estado.md

i18n/pt-BR/articles/contexto-data.md
=> Tradução: i18n\pt-BR\articles\contexto-data.md

i18n/pt-BR/articles/requisicao-e-resposta-do-servidor.md
Está ai mano,
eu acho que algumas partes ficaram meio sem sentido com a minha tradução,
pode me dar um feedback sobre isso?
também queria saber sobre uns termos tipo *server-side rendering*, *request*, *response* é necessário traduzir eles ou pode manter em inglês?
=> docs(request-response): translating doc to pt-BR

i18n/en-US/components/Contributors.yml, i18n/pt-BR/components/Contributors.yml, src/Contributors.njs
=> Reviewing and updating Contributors page

i18n/pt-BR/articles/instancia-self.md
Traduzindo a secção Instância-self da documentação para português
=> docs(instancia-self): translating doc to pt-BR

i18n/pt-BR/articles/instancia-key.md
=> docs(instancia-key): translating doc to pt-BR

i18n/en-US/articles/context-data.md, i18n/en-US/articles/context-instances.md, i18n/en-US/articles/context.md, i18n/en-US/components/Documentation.yml, i18n/pt-BR/articles/contexto-data.md, i18n/pt-BR/articles/contexto-instances.md, i18n/pt-BR/articles/contexto.md, i18n/pt-BR/components/Documentation.yml
=> Adding context instances doc in EN/BR

i18n/en-US/articles/renderable-components.md, i18n/pt-BR/articles/componentes-renderizaveis.md
=> Add Fragments docs in EN/BR

i18n/en-US/articles/application-startup.md, i18n/en-US/articles/functional-components.md, i18n/en-US/articles/renderable-components.md, i18n/en-US/components/Documentation.yml, i18n/pt-BR/articles/componentes-funcionais.md, i18n/pt-BR/articles/componentes-renderizaveis.md, i18n/pt-BR/articles/inicializacao-da-aplicacao.md, i18n/pt-BR/components/Documentation.yml
=> Add functional components docs in EN/BR

i18n/en-US/articles/service-worker.md, i18n/pt-BR/articles/service-worker.md
=> Update doc for worker.queues in EN/BR

i18n/pt-BR/articles/geracao-de-sites-estaticos.md
Tag with undefined error e title doesn't appear
=> Fix tags on static site pt-br

i18n/pt-BR/articles/renderizando-no-servidor.md
Parabéns pelo projeto, muito interessante, conheci recentemente.
Segue a tradução com a correção dos links #29
=> Add translation renderizando-no-servidor #29

i18n/en-US/articles/functional-components.md, i18n/en-US/articles/instance-self.md, i18n/en-US/articles/persistent-components.md, i18n/en-US/components/Documentation.yml, i18n/pt-BR/articles/componentes-funcionais.md, i18n/pt-BR/articles/componentes-persistentes.md, i18n/pt-BR/articles/instancia-self.md, i18n/pt-BR/components/Documentation.yml
=> Add docs for Persistent Components EN/BR

i18n/pt-BR/articles/como-usar-mongodb-com-nullstack.md
the env variable is NULLSTACK_SECRETS_MONGODB_URI so the secret should be mongodbUri
=> fix: reference database uri - BR

i18n/pt-BR/components/Home.yml, src/Article.njs
=> Fix article-menu width responsivity

i18n/en-US/articles/getting-started.md, i18n/pt-BR/articles/comecando.md
Depends on https://github.com/nullstack/create-nullstack-app/pull/32
=> Explain use of create-nullstack-app TS flags

i18n/en-US/articles/routes-and-params.md, i18n/pt-BR/articles/rotas-e-parametros.md
=> Add docs about router.previous

i18n/en-US/components/Waifu.yml
=> Fixes a small typo in the Waifu page.

i18n/en-US/components/Blog.yml, i18n/en-US/components/Header.yml, i18n/en-US/posts/404.md, i18n/en-US/posts/release-candidate-announcement.md, src/Application.njs, src/Blog.njs, src/Header.njs, src/Post.njs, tailwind.css
Adds blog engine to the website and the first post - RC announcement
=> :sparkles: blog engine and rc announcement
